### ISSUE TITLE
Adding a Docker image build that we could use on EOSC or any other place

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/foss4g-2022#20]
I guess it would be nice to have a Docker image we could just pull to start Dask cluster on EOSC infra or any other K8S Jupyterhub or even on any laptop to reproduce tutorial prepared here.

I'm not sure if this was already done by @tinaok or any of you in some other repo? Should it go here or in Pangeo-eosc repo ? (I would say here because env is related to Foss4g application).

I've done something similar in https://github.com/guillaumeeb/pangeo-docker by extending Pangeo docker images. I can work on this if you feel this is interesting and you didn't do it yet.

**Comment by acocac** [comment]
The Docker image setting looks interesting. I think it should be placed in the Pangeo-eosc repo. @tinaok is on leave, but I hope she can assist on your request in her return.

**Comment by tinaok** [comment]
Hi, 
as you can refer to the configuration of EGI-EOSC pangeo configuration [here](https://github.com/grycap/im-dashboard/blob/devel/tosca-templates/daskhub.yaml)

we use docker image of 
[pangeo/pangeo-notebook:latest](https://hub.docker.com/r/pangeo/pangeo-notebook)
Which is based on [this package list](https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/packages.txt) 


Certain specific package (cf the one we needed for discovering data on @acocac  or @pl-marasco 's example notebooks) I intentionally kept 'pip install' only for non Pangeo-notebook packages,  so the people can start from well equipped pangeo docker image, but if they have specific environment to add in future, they can learn how to do it an 'easy' way.  

So for 'requirement.txt', I suggest we link it to Pangeo-notebook/packages.txt (or the docker image).  (I think binder config, we can specify docker image? @annefou ?)  It might gets heavy but we are sure the new user will not get discouraged due to having 'wrong versions of libxxx and things does not work, and have to google for hours to find the right version...' 

There were some discussions in some issue or pull request #39 (sorry I didn't check all issue yet)  jupyter lab or dask lab extension, graphviz etc are all in the Pangeo-notebook/packages.txt  .

**Comment by guillaumeeb** [comment]
I understand that we are using this image for the Jupyter notebook server only currently.

It is also good to know for users they can pip or conda install things in a notebook running in a docker environment, but this is not always feasible. 

The problems get tricky as discussed in https://github.com/pangeo-data/pangeo-eosc/issues/3, we are not using the same base image for Dask Client and Scheduler/Workers. 

And I also think it would be easier for the workshop if users didn't have to worry about installing package at all.

For the environment.yaml of this repo, problem is it is also used for building the book, so it contains other package as the ones from Pangeo-notebook.

**Comment by guillaumeeb** [comment]
We could also use a different environment for Binder and for building the book in CI. Ideally we should execute the notebooks during the build with the same environment as the one we will use during the workshop.

In any cases, I think we should at least use the same Docker image for the Notebook pod and for Dask-gateway launched pods.

**Comment by guillaumeeb** [comment]
A quick check on our environment.yaml vs pangeo-notebook image, pangeo-notebook images lacks:
- jupyter-book,
- ipycytoscape,
- ghp-import,
- has only geoview-core instead of geoviews
- uses Python 3.9 instead of 3.10.

When executing the notebooks, I did not notice a package installation on the notebook side (as we don't use openEO anymore). This would mean that for executing notebooks, the pangeo-notebook image is enough? And thus, that even if we cannot use it for build, we can use it for execution and don't need to build another one?

@acocac @pl-marasco @tinaok @annefou do you intend to use a library that would not be in the pangeo-notebook image?

**Comment by acocac** [comment]
@guillaumeeb `pooch` (used to fetch data from Zenodo for some notebooks in Pangeo 101) and `odc-stac` (wildfires example) aren't listed in the pangeo-notebook docker image.

**Comment by guillaumeeb** [comment]
Pooch is there: https://github.com/pangeo-data/pangeo-docker-images/blob/63db2c11fb3ec84a96d87a9457b3e9813c73aff2/pangeo-notebook/packages.txt#L413.

So that leaves odc-stac missing. I haven't look closely, bit I think we don't use it with dask-gateway?

**Comment by acocac** [comment]
We can try to replace `odc-stac` with `stackstac`, both turn a STAC collection into a lazy `xarray.DataArray`.

**Comment by guillaumeeb** [comment]
I propose we close this issue if we only need to add 2 or 3 packages on the Jupyter notebook side.

If we need them also on workers of dask-gateway, then it's better to build an image.
